# Generated by Django 4.1.6 on 2023-02-28 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_breed', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=255)),
                ('breed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petbreed', to='accounts.petbreed')),
            ],
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='breedname', to='accounts.petbreed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pettype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='breedtype', to='accounts.pettype'),
            preserve_default=False,
        ),
    ]
