# Generated by Django 4.1.6 on 2023-02-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_petbreed_pettype_alter_petprofile_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='petimage',
            field=models.FileField(default=1, max_length=254, upload_to=None),
            preserve_default=False,
        ),
    ]
