# Generated by Django 4.1.6 on 2023-02-28 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_petprofile_petimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('pet_breed', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.petbreed')),
                ('pet_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.pettype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
