# Generated by Django 4.1.6 on 2023-02-28 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pet_breed',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AddField(
            model_name='petprofile',
            name='petimage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='breedtype', to='accounts.image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(max_length=254, upload_to=None),
        ),
    ]
