# Generated by Django 4.1.6 on 2023-02-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_image_pet_breed_remove_image_pet_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(max_length=254, upload_to='images/'),
        ),
    ]
