# Generated by Django 4.1.6 on 2023-03-01 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pet_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='petprofile', to='accounts.petprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=254, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='petimage',
            field=models.ImageField(upload_to=''),
        ),
    ]
