# Generated by Django 4.1.6 on 2023-03-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_image_pet_profile_alter_image_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petprofile',
            name='petimage',
        ),
    ]
