# Generated by Django 4.1.6 on 2023-03-07 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_pet_id_image_pet_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petprofile',
            old_name='breed',
            new_name='petbreed',
        ),
        migrations.AddField(
            model_name='petprofile',
            name='petimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='pet_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_name', to='accounts.petprofile'),
        ),
    ]
