# Generated by Django 4.1.6 on 2023-03-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_breed_petprofile_petbreed_petprofile_petimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pet_profile',
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='petgender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=250, null=True),
        ),
    ]
