# Generated by Django 4.1.6 on 2023-03-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_image_pet_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='upload_images',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=''),
        ),
    ]
