# Generated by Django 4.1.6 on 2023-03-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_petprofile_upload_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petprofile',
            name='upload_images',
        ),
    ]
